### ISSUE TITLE
MacOS Arm64 does not display windows

### ISSUE THREAD

**Issue by Yeffian** [electronstudio/jaylib#43]
System Information:
M2 Macbook Air
Sonoma 14.3.1

Trying to compile my project which depends on Jaylib results in the following error:
```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "macosx-arm64" not supported by class com.raylib.Raylib
	at org.bytedeco.javacpp.Loader.load(Loader.java:1184)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
	at com.raylib.Raylib.<clinit>(Raylib.java:10)
	at dev.yeff.orbital.graphics.Window.start(Window.java:39)
	at dev.yeff.orbital.Game.start(Game.java:45)
	at dev.yeff.Main.main(Main.java:21)
```

Does Jaylib not support MacOS, or is there something I need to add myself, like an extra dependency, etc.?

**Comment by Yeffian** [comment]
Details of Java version attached below

<img width="555" alt="Screenshot 2024-04-12 at 10 55 50 AM" src="https://github.com/electronstudio/jaylib/assets/76024824/d61060b6-910f-4c32-9946-43b0a98d59d6">

**Comment by Yeffian** [comment]
https://github.com/electronstudio/jaylib/discussions/40#discussioncomment-9091669
